### PR TITLE
Add HubspotFormProps missing types

### LINKED ISSUE #134: Configuration option for region is not included in HubspotFormProps
**Describe the bug**

**To Reproduce**
1. Add a component and use the Region property
2. I get a typescript error saying: `Property 'region' does not exist on type 'IntrinsicAttributes & HubspotFormProps'`

**Expected behavior**

### PR DESCRIPTION
**Pull request by mcortes19**
Close #134

### CODE REVIEW

**Comment by snelsi** [comment]
Looks good, but why did you remove `blockedDomains` property?

**Comment by mcortes19** [comment]
> blockedDomains

According to the [official specification](https://legacydocs.hubspot.com/docs/methods/forms/advanced_form_options) `blockedDomains ` is no longer an accepted property

**Comment by snelsi** [comment]
I see, thanks for the clarification

**Review by snelsi — APPROVED** [review]
lgtm

**Comment by snelsi** [comment]
Published as [`v1.3.0`](https://github.com/snelsi/next-hubspot/releases/tag/1.3.0)

**Pull request merged**
